// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWFC.Infrastructure.Persistence.Context;

#nullable disable

namespace SWFC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416160113_AddM205Energy")]
    partial class AddM205Energy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Assignments.UserOrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OrganizationUnitId")
                        .IsUnique();

                    b.ToTable("UserOrganizationUnits", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Assignments.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.OrganizationUnits.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentOrganizationUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrganizationUnits", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityKey")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.MachineComponentAreas.MachineComponentArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MachineComponentAreas", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.MachineComponents.MachineComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MachineComponentAreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentMachineComponentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MachineComponentAreaId");

                    b.HasIndex("ParentMachineComponentId");

                    b.HasIndex("MachineId", "Name");

                    b.ToTable("MachineComponents", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentMachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("ParentMachineId");

                    b.ToTable("Machines", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M202_Maintenance.MaintenanceOrders.MaintenanceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceOrders", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M202_Maintenance.MaintenancePlans.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalUnit")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaintenancePlans", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Reservations.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockReservations", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Stock.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("InventoryItemId", "LocationId", "Bin")
                        .IsUnique();

                    b.ToTable("Stocks", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Stock.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockMovements", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M205_Energy.EnergyMeters.EnergyMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<int>("MediumType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EnergyMeters", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M205_Energy.EnergyReadings.EnergyReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("EnergyReadings", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M800_Security.M805_AuditCompliance.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M800_Security.M801_Access.AccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId", "SubjectType", "SubjectId")
                        .IsUnique();

                    b.ToTable("AccessRules", "core");
                });

            modelBuilder.Entity("SWFC.Infrastructure.M100_System.M103_Authentication.Entities.LocalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastPasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LocalCredentials", "core");
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Assignments.UserOrganizationUnit", b =>
                {
                    b.HasOne("SWFC.Domain.M100_System.M102_Organization.Users.User", null)
                        .WithMany("OrganizationUnits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("UserOrganizationUnitId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("UserOrganizationUnitId");

                            b1.ToTable("UserOrganizationUnits", "core");

                            b1.WithOwner()
                                .HasForeignKey("UserOrganizationUnitId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Assignments.UserRole", b =>
                {
                    b.HasOne("SWFC.Domain.M100_System.M102_Organization.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("UserRoleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("UserRoleId");

                            b1.ToTable("UserRoles", "core");

                            b1.WithOwner()
                                .HasForeignKey("UserRoleId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.OrganizationUnits.OrganizationUnit", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("OrganizationUnitId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("OrganizationUnitId");

                            b1.ToTable("OrganizationUnits", "core");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationUnitId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Roles.Role", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("RoleId");

                            b1.ToTable("Roles", "core");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Users.User", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "core");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.MachineComponentAreas.MachineComponentArea", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("MachineComponentAreaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("MachineComponentAreaId");

                            b1.ToTable("MachineComponentAreas", "core");

                            b1.WithOwner()
                                .HasForeignKey("MachineComponentAreaId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.MachineComponents.MachineComponent", b =>
                {
                    b.HasOne("SWFC.Domain.M200_Business.M201_Assets.MachineComponentAreas.MachineComponentArea", null)
                        .WithMany()
                        .HasForeignKey("MachineComponentAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SWFC.Domain.M200_Business.M201_Assets.Machines.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SWFC.Domain.M200_Business.M201_Assets.MachineComponents.MachineComponent", null)
                        .WithMany()
                        .HasForeignKey("ParentMachineComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("MachineComponentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("MachineComponentId");

                            b1.ToTable("MachineComponents", "core");

                            b1.WithOwner()
                                .HasForeignKey("MachineComponentId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.Machines.Machine", b =>
                {
                    b.HasOne("SWFC.Domain.M200_Business.M201_Assets.Machines.Machine", "ParentMachine")
                        .WithMany("Children")
                        .HasForeignKey("ParentMachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines", "core");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentMachine");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M202_Maintenance.MaintenanceOrders.MaintenanceOrder", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("MaintenanceOrderId");

                            b1.ToTable("MaintenanceOrders", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M202_Maintenance.MaintenanceOrders.MaintenanceOrderDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("MaintenanceOrderId");

                            b1.ToTable("MaintenanceOrders", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");
                        });

                    b.OwnsMany("SWFC.Domain.M200_Business.M202_Maintenance.MaintenanceOrders.MaintenanceOrderMaterial", "Materials", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MaintenanceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("MaintenanceOrderId");

                            b1.ToTable("MaintenanceOrderMaterials", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");

                            b1.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b2 =>
                                {
                                    b2.Property<Guid>("MaintenanceOrderMaterialId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("CreatedAtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("CreatedAtUtc");

                                    b2.Property<string>("CreatedBy")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("CreatedBy");

                                    b2.Property<DateTime?>("LastModifiedAtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("LastModifiedAtUtc");

                                    b2.Property<string>("LastModifiedBy")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("LastModifiedBy");

                                    b2.HasKey("MaintenanceOrderMaterialId");

                                    b2.ToTable("MaintenanceOrderMaterials", "core");

                                    b2.WithOwner()
                                        .HasForeignKey("MaintenanceOrderMaterialId");
                                });

                            b1.Navigation("AuditInfo")
                                .IsRequired();
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M202_Maintenance.MaintenanceOrders.MaintenanceOrderNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Number");

                            b1.HasKey("MaintenanceOrderId");

                            b1.ToTable("MaintenanceOrders", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M202_Maintenance.MaintenanceOrders.MaintenanceOrderTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Title");

                            b1.HasKey("MaintenanceOrderId");

                            b1.ToTable("MaintenanceOrders", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Materials");

                    b.Navigation("Number")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M202_Maintenance.MaintenancePlans.MaintenancePlan", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("MaintenancePlanId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("MaintenancePlanId");

                            b1.ToTable("MaintenancePlans", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenancePlanId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M202_Maintenance.MaintenancePlans.MaintenancePlanDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("MaintenancePlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("MaintenancePlanId");

                            b1.ToTable("MaintenancePlans", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenancePlanId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M202_Maintenance.MaintenancePlans.MaintenancePlanName", "Name", b1 =>
                        {
                            b1.Property<Guid>("MaintenancePlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("MaintenancePlanId");

                            b1.ToTable("MaintenancePlans", "core");

                            b1.WithOwner()
                                .HasForeignKey("MaintenancePlanId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItem", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemArticleNumber", "ArticleNumber", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ArticleNumber");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemBarcode", "Barcode", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Barcode");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Description");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemManufacturer", "Manufacturer", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Manufacturer");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemManufacturerPartNumber", "ManufacturerPartNumber", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ManufacturerPartNumber");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemName", "Name", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItemUnit", "Unit", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Unit");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems", "core");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("ArticleNumber")
                        .IsRequired();

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Barcode");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("ManufacturerPartNumber");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Unit")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Locations.Location", b =>
                {
                    b.HasOne("SWFC.Domain.M200_Business.M204_Inventory.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations", "core");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Locations.LocationCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Code");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations", "core");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M204_Inventory.Locations.LocationName", "Name", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations", "core");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Reservations.StockReservation", b =>
                {
                    b.HasOne("SWFC.Domain.M200_Business.M204_Inventory.Stock.Stock", null)
                        .WithMany("Reservations")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("StockReservationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("StockReservationId");

                            b1.ToTable("StockReservations", "core");

                            b1.WithOwner()
                                .HasForeignKey("StockReservationId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Stock.Stock", b =>
                {
                    b.HasOne("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItem", null)
                        .WithMany("Stocks")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SWFC.Domain.M200_Business.M204_Inventory.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("StockId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("StockId");

                            b1.ToTable("Stocks", "core");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Stock.StockMovement", b =>
                {
                    b.HasOne("SWFC.Domain.M200_Business.M204_Inventory.Stock.Stock", null)
                        .WithMany("Movements")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("StockMovementId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("StockMovementId");

                            b1.ToTable("StockMovements", "core");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M205_Energy.EnergyMeters.EnergyMeter", b =>
                {
                    b.OwnsOne("SWFC.Domain.M200_Business.M205_Energy.EnergyMeters.EnergyExternalSystem", "ExternalSystem", b1 =>
                        {
                            b1.Property<Guid>("EnergyMeterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ExternalSystem");

                            b1.HasKey("EnergyMeterId");

                            b1.ToTable("EnergyMeters", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyMeterId");
                        });

                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("EnergyMeterId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("EnergyMeterId");

                            b1.ToTable("EnergyMeters", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyMeterId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M205_Energy.EnergyMeters.EnergyMeterName", "Name", b1 =>
                        {
                            b1.Property<Guid>("EnergyMeterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("EnergyMeterId");

                            b1.ToTable("EnergyMeters", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyMeterId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M205_Energy.EnergyMeters.EnergyMeterUnit", "Unit", b1 =>
                        {
                            b1.Property<Guid>("EnergyMeterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Unit");

                            b1.HasKey("EnergyMeterId");

                            b1.ToTable("EnergyMeters", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyMeterId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ExternalSystem");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Unit")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M205_Energy.EnergyReadings.EnergyReading", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("EnergyReadingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("EnergyReadingId");

                            b1.ToTable("EnergyReadings", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyReadingId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M205_Energy.EnergyReadings.EnergyReadingDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("EnergyReadingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ReadingDate");

                            b1.HasKey("EnergyReadingId");

                            b1.ToTable("EnergyReadings", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyReadingId");
                        });

                    b.OwnsOne("SWFC.Domain.M200_Business.M205_Energy.EnergyReadings.EnergyReadingValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("EnergyReadingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("ReadingValue");

                            b1.HasKey("EnergyReadingId");

                            b1.ToTable("EnergyReadings", "core");

                            b1.WithOwner()
                                .HasForeignKey("EnergyReadingId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M800_Security.M801_Access.AccessRule", b =>
                {
                    b.OwnsOne("SWFC.Domain.M100_System.M101_Foundation.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessRuleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAtUtc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedAtUtc");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("AccessRuleId");

                            b1.ToTable("AccessRules", "core");

                            b1.WithOwner()
                                .HasForeignKey("AccessRuleId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Infrastructure.M100_System.M103_Authentication.Entities.LocalCredential", b =>
                {
                    b.HasOne("SWFC.Domain.M100_System.M102_Organization.Users.User", null)
                        .WithOne()
                        .HasForeignKey("SWFC.Infrastructure.M100_System.M103_Authentication.Entities.LocalCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWFC.Domain.M100_System.M102_Organization.Users.User", b =>
                {
                    b.Navigation("OrganizationUnits");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M201_Assets.Machines.Machine", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Items.InventoryItem", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("SWFC.Domain.M200_Business.M204_Inventory.Stock.Stock", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}

