name: Branch Name Check

on:
  pull_request:

jobs:
  branch-name-check:
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch name
        run: |
           = 
          echo "Branch: "
          if [[ ! "" =~ ^(feature|fix|chore|refactor|test)/M[0-9]{3,4}\.[0-9]{2}-[a-z0-9-]+$ ]]; then
            echo "Invalid branch name: "
            exit 1
          fi