name: Commit Message Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate commit messages
        run: |
          git log origin/main..HEAD --pretty=format:%s | grep -E "^\[M[0-9]{3}\.[0-9]{2}\]" || (echo "❌ Invalid commit message format. Use [Mxxx.xx]" && exit 1)