name: Commit Message Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get last commit message
        run: |
          msg=$(git log -1 --pretty=%s)
          echo "Commit message: $msg"
          echo "$msg" | grep -E "^\[M[0-9]{3}\.[0-9]{2}\]" || (echo "❌ Invalid commit message format. Use [Mxxx.xx]" && exit 1)